core:
  pager: "bat"
  pager_arguments:
    - "--theme=Sublime Snazzy"
git:
  merging:
    args: mergetool
  pagers:
    - pager: delta --dark --paging=never --syntax-theme="Sublime Snazzy"
      colorArg: never
  commit:
    signOff: true
