core:
  pager: "bat"
  pager_arguments:
    - "--theme=gruvbox-light"
git:
  merging:
    args: mergetool
  pagers:
    - pager: delta --light --paging=never
      colorArg: never
  commit:
    signOff: true
