[font]
size = 12

[font.normal]
family="JetBrainsMono Nerd Font"

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 7
y = 0

[colors.primary]
background = '#f9f5d7'
foreground = '#654735'

[colors.normal]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#f2e5bc'

[colors.bright]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#f2e5bc'
